# Generated by Django 4.2.11 on 2024-04-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booksmodel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=11)),
                ("author", models.CharField(max_length=10)),
                ("copies", models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name="Book",
        ),
    ]
